---
- name: Install stunnel4
  with_items:
    - stunnel4

  apt: name={{ item }} state=present

- name: Creating custom configuration for services
  template:
    src="conf.j2"
    dest="/etc/stunnel/{{ stunnel_service_name }}.conf"
    owner="{{ stunnel_owner }}"
    group="{{ stunnel_group }}"
    mode="0644"

- name: Enabling stunnel
  lineinfile: dest=/etc/default/stunnel4 regexp=^ENABLED line=ENABLED=1
  
- name: Stopping stunnel4
  service: name=stunnel4 state=stopped
  
- name: Starting stunnel4
  service: name=stunnel4 state=started 
  
